language: python

python:
 - "2.7"
 - "3.4"
 
script:
 - python helloworld.py
 - python hellocaleb.py
 - sh test_helloChris.sh
 - sh testAllyn.sh
 - python hellomaria.py
 - python helloKevin.py
 - sh testKevin.sh
 
#before_install:
# - pip 
